fruits=["Apple","Mangoes",[10,20,30],"Oranges","banana","lemon"]
print(fruits)
#indexing
print(fruits[2])
#slicing
print(fruits[1:4])
print(fruits[2])
print(fruits[2][1])
my_list=[10,20,30,"python","html"]
my_list[4]="css"
print(my_list)
print(len(my_list))
my_list.append("python")
print(my_list)
my_list.append("1000")
print(my_list)
my_list.clear()
print(my_list)
my_list.copy()
my_list=my_list.copy()
print(my_list)
my_list.insert(1,44)
print(my_list)
my_list.remove(44)
print(my_list)
my_list
